[package]
name = "orchestra-rs"
version = "0.2.0"
edition = "2024"
description = "An orchestration framework for building AI agents using multiple LLM providers."
keywords = [
    "AI",
    "ai-agents",
    "gemini",
    "generative-ai",
    "open-ai",
]
repository = "https://github.com/ayoubbuoya/orchestra-rs"
readme = "README.md"
license = "MIT"
authors = ["Ayoub Amer <ayouub.ameur@gmail.com>"]


[dependencies]

