[package]
name = "orchestra-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = "0.12.23"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
thiserror = "2.0.16"
url = "2.5.4"
